<form id="<?php  print $this->form->getname()?>"  name="<?php print $this->form->getname()?>" 
action="<?php print $this->form->getaction()?>" 
method="POST" enctype="application/x-www-form-urlencoded">
<div class="menu-botones ">
	<div class="pull-left"><h4>Crear Distribución</h4></div>
		<div class="pull-right">
		<?php print $this->form->save?>
		<a href="/admin/module/" class="btn btn-danger" >CANCELAR</a>
		</a>
		
	</div>
</div>
<table class="table table-striped table-hover ">
      <tr>
      	<th class="col-lg-2">Nombre Sistema</th>
      	<td><div class="col-lg-4"><?php echo $this->form->name?></div></td>
      </tr>
      <tr>
      	<th class="col-lg-2">Nombre Modulo</th>
      	<td><div class="col-lg-3"><?php echo $this->form->module?></div></td>
      </tr>
      <tr>
      	<th class="col-lg-2">Icono</th>
		<td><div class="col-lg-2"><?php echo $this->form->imgicon?></div></td>
      </tr>	
      <tr>
        <th class="col-lg-2">Estado</th>
		<td><div class="col-lg-2"><?php echo $this->form->state?></div></td>
      </tr>
   </table>
</form>