<?php
if ($this->datos)
{
?>
<table class="table table-hover">
    <thead>
    <tr>
        <th class='text-center'>#</th>                
        <th class='text-center'>DNI</th>
        <th class='text-center'>Cod. Mat.</th>
        <th class='text-center'>Nombres y Apellidos</th>
        <th class='text-center'>Escuela</th>
        <th class='text-center'>Operaciones</th>
    </tr>
    </thead>

<?php
    $i=0;
    foreach ($this->datos as $datos)    
    {
        $i++;
       ?>
        <tr>
            <td class='text-center'><?php echo $i?></td>
            <td class='text-center'><?php echo $datos['pid'];?></td>
            <td class='text-center'><?php echo $datos['uid'];?></td>
            <td><?php echo $datos['last_name0']." ".$datos['last_name1'].", ".$datos['first_name'];?></td>
            <td class='text-center'><?php echo $datos['escid']?></td>
            <td class='text-center'>
                <a href='#' class='keychange' data-toggle="modal" data-target="#myModal" eid="<?php echo base64_encode($datos['eid'])?>" oid="<?php echo base64_encode($datos['oid'])?>" rid="<?php echo base64_encode($datos['rid'])?>" uid="<?php echo base64_encode($datos['uid'])?>" pid="<?php echo base64_encode($datos['pid'])?>" escid="<?php echo base64_encode($datos['escid'])?>" subid="<?php echo base64_encode($datos['subid'])?>"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
       <?php
    }
    ?>
</table>
<?php
}
else{   ?>  
    <div class='col-md-8 col-xs-offset-2 cont-font-not-register alert alert-danger'>
    <h3 class='text-not-register'><b>NO SE ENCONTRARON REGISTROS</b></h3>
    <h1 class='span-not-register'>
        <span class='glyphicon glyphicon-exclamation-sign' ></span>
    </h1>
</div>
<?php
}
?>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <center><h3 class="modal-title" id="myModalLabel"><b class='text-primary'>Nueva Contraseña</b></h3></center>
            </div>
            <div class="modal-body">
                <div id='change'></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(".keychange").click( function(){
        var params = {
        eid:$(this).attr('eid'),
        oid:$(this).attr('oid'),
        rid:$(this).attr('rid'),
        uid:$(this).attr('uid'),
        pid:$(this).attr('pid'),
        escid:$(this).attr('escid'),
        subid:$(this).attr('subid')
        };
        $.get("/admin/password/keychange/",
            params,
            function  (data) {
                $('#change').html("<center><img src='/img/spinner.gif'> Cargando...</center>");
                $("#change").html(data);
        });
    });
</script>