<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-qrcode"></span> CAMBIAR CLAVE');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>

<div style="text-align: right;">
    <button id="buscar" type="button" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Buscar</button>
</div>
</br>
<form id="cambiaclave" name="<?php echo $this->fm->getName(); ?>" action="<?php echo $this->fm->getAction(); ?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >        
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <center>
            <table class='table table-hover'>
                <tr >
                    <th class='text-right' style='font-size:15px'>Código : </th>
                    <td><div class='col-xs-4 col-xs-offset-1'><?php echo $this->fm->uid;?></div></td>
                </tr>
                <tr >
                    <th class='text-right' style='font-size:15px'>Apellidos y Nombres : </th>
                    <td><div class='col-md-9 col-xs-offset-1'><?php echo $this->fm->nom; ?></div></td>
                    <!-- <td><input |type="text" name="nom" id="nom" ></td> -->
                </tr>
                <tr >
                    <th class='text-right' style='font-size:15px'>Rol : </th>
                    <td><div class='col-md-12 col-xs-offset-1'><?php echo $this->fm->chrol; ?></div></td>
                </tr>
            </table>
        </center>
    </div>    
</div> 
</form>
<div id="datos"></div>

<script>

$("#buscar").click(function(){
    if ($("#uid").val() || $("#nom").val()) {
        vuid = $("#uid").val();
        vnom = $("#nom").val();
        
        url="/admin/password/list/uid/" + vuid +"/nom/" + vnom + "/rol/" + rol;
        $('#datos').html("<center><img src='/img/spinner.gif'> Cargando....</center>");
        $("#datos").load(url);
        return false;
    }else{
        alert ("Escriba un Código ó Apellidos y Nombres");
    };
});
rol='';
$("#chrol-docente").change(function(){
    rol = $(this).val();
    $("#rol").attr("value",rol);
   });

$("#chrol-alumno").change(function(){
    rol = $(this).val();
    $("#rol").attr("value",rol);
   });

</script>