<form action="/admin/acl/new" method="POST">
	<div class="modal-dialog">
	  	<div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	          <h4 class="modal-title">Nuevo Modulo</h4>
	        </div>
	        <div class="modal-body">
	          	<label>Nombre</label>
				<?php echo $this->form->name?>
				<label>Icono</label>
				<?php echo $this->form->imgicon?>
				<label>Modulo</label>
				<?php echo $this->form->module?>
	        </div>
	        <div class="modal-footer">
	          <?php echo $this->form->save ?>
	        </div>
	  	</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form>