<form id="frmrol" name="frmrol" action="/admin/rol/update/" method="POST" enctype="application/x-www-form-urlencode">
<!-- 	<div class="span10 flotacarajo">
    	<table class="table table-hover span9">
        	<tr>
            	<th style="font-size:20px;"><br>
                	MODIFICAR EL ROL
                  	<div style="float:right; margin-left:10px"><?php echo $this->form->send?></div><br>
                  	<a style="float:right" class="btn btn-danger" href="/admin/rol/">Cancelar</a>
            	</th>
        	</tr>
    	</table>
	</div> -->
	<div class="row">
        <div class='col-md-2'>Cod.Rol:</div>
        <div class='col-md-4'><?php echo $this->form->rid?></div>
        <div class='col-md-2'>Prefijo:</div>
        <div class='col-md-4'><?php echo $this->form->prefix?></div>   
    </div></br></br> 
    <div class="row">
        <div class='col-md-2 col-sm-offset-1'>Nombre:</div>
        <div class='col-md-6 col-sm-offset-1'><?php echo $this->form->name?></div>
    </div></br></br>
    <div class="row">        
        <div class='col-md-2 col-sm-offset-1'>Módulo :</div>
        <div class='col-md-6 col-sm-offset-1'><?php echo $this->form->module?></div> 
    </div></br></br>
    <div class="row">
        <div class='col-md-2 col-sm-offset-1'>Estado :</div>
        <div class='col-md-6 col-sm-offset-1'><?php echo $this->form->state?></div>
    </div></br></br>
    <input type="hidden" name ="rid" value="<?php echo base64_encode($this->rid)?>">  
</form>

<div class="modal-footer">
    <button id="supdaterol" type="button" class="btn btn-success"><span class='glyphicon glyphicon-save'></span> Actualizar</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
</div>
<script type="text/javascript">
	$("#supdaterol").click(function(){   
        var url="/admin/rol/update/";
        $.ajax({
            url: url,
            type: 'POST',
            data:$("#frmrol").serialize(),
            success: function (data){
                $("#mo_rol").html(data)
            }
        });
    });

    var valor="<?php echo $this->valor?>";
    if (valor==2) {
        $('#myModal1').modal('hide');
        $('#myModal1').on('hidden.bs.modal', function (e) {
            $(location).attr("href", "/admin/rol/")
        });
    };
</script>