<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-user"></span> GESTION DE USUARIOS');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>

<form name="<?php echo $this->fm->getName(); ?>" id ="frmFiltroDoc" action="/admin/user/getuser" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
    <table class="table span9 table-striped table-bordered table-condensed">
        <tr class="info">
            <td colspan='2' class="text-center"><span class='glyphicon glyphicon-exclamation-sign text-danger'> </span> <span class="text-muted"> Busque Usuarios por uno de los siguientes campos</span></td>
            <td><a href="/admin/user/new" style='float:right' class='btn btn-info'><span class='glyphicon glyphicon-plus'></span> Nuevo Usuario</a></td>
        </tr>
        <tr style="background:black ;color:white;font-weight: 900;">
            <td><center>Buscar por DNI</center></td>
            <td><center>Buscar por Nombres y Apellidos</center></td>
            <td><center>Buscar por Código Usuario</center></td>
        </tr>
        <tr>
            <td><center><?php echo $this->fm->pid ?></center></td>
            <td><center><?php echo $this->fm->name ?></center></td>
            <td><center><?php echo $this->fm->uid ?></center></td>
        </tr>
    </table>
    <div class="row">
        <div class="col-md-offset-5 col-md-2">
            <button type="button" id="btnBuscar" data-loading-text="buscando..." class="btn btn-success form-control"><span class='glyphicon glyphicon-search'></span> Buscar</button>
        </div>
    </div>
    
</form>
<br><br>
<div  id="cargadatos_">
    <!--lista de usuarios -->
</div> 
<script>
    $(function(){
        $("#name").focus(function() {
            $("#pid").val("");
            $("#uid").val("");
        });
        $("#pid").focus(function() {
            $("#name").val("");
            $("#uid").val("");
        });
        $("#uid").focus(function() {
            $("#name").val("");
            $("#pid").val("");
        });
    });

    $("#name, #pid, #uid").keypress(function (e) {
        if(e == 13 || e.which==13 || e.which==0){
            var codi =  $('#pid').val();
            var nom =  $('#name').val();
            count=codi.length;
            if (count==8 || count==0)
            {
                btn = $("#btnBuscar")
                enviarDatos();
                btn.button('loading')
            }
            else
            {
                alert("Ingrese un DNI valido");
                $('#pid').val('');
                $('#pid').focus();
            }
            var codi1 = $('#uid').val();
            count1=codi1.length;
            if (count1==10 || count1==0) {
                btn = $("#btnBuscar")
                enviarDatos();
                btn.button('loading')
            }
            else
            {
                alert("Ingrese un Código válido");
                $('#uid').val('');
                $('#uid').focus();
            }   
        }
    });
    var btn;
    $("#btnBuscar").click(function() {
        btn = $(this)
        enviarDatos();
        btn.button('loading')
    });
    function enviarDatos() {
        $('#cargadatos_').html("<img src='/img/spinner.gif'> Cargando....");
        var formu = $("#frmFiltroDoc");
        $.ajax({
            type: 'POST',
            url: formu.attr('action'),
            data: formu.serialize(),
            success: function(data) {
                $('#cargadatos_').html(data);
                btn.button('reset');
            }
        }); 
        return false;
    }

function validNumber(e) {
    var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
    }
function soloLetras(e){
       key = e.keyCode || e.which;
       tecla = String.fromCharCode(key).toLowerCase();
       letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
       especiales = [8,37,39,46];

       tecla_especial = false
       for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }
        if(letras.indexOf(tecla)==-1 && !tecla_especial){
            return false;
        }
    }     
</script>