<table>
<tr>
	<th>Sede: </th>
	<td><div style='width: 200px'><?php echo $this->fm->subid;?></td>
	<th>Escuela: </th>
	<td><div style='width: 200px'><?php echo $this->fm->escid;?></td>
</tr>
<tr>
	<th>Rol: </th>
	<td><div style='width: 200px'><?php echo $this->fm->rid?></td>
	<th>Estado: </th>
	<td><div style='width: 200px'><?php echo $this->fm->state?></td>
</tr>	
<tr>
	<th>Resolución:</th>
	<td><div style='width: 200px'><?php echo $this->fm->resolution?></td>
</tr>
<tr>
	<td><?php echo $this->fm->Guardar?></td>
</tr>	
</table>