<form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">
<div class="menu-botones">
	<div class="pull-left"><h4>Crear Recurso</h4></div>
	<div class="pull-right">
	<?php print $this->form->save?>
	<a href="/docente/distribution/" class="btn btn-danger" >CANCELAR</a>
	</a>
	</div>
</div>

<table class="table table-striped table-bordered">
	<tr>
		<td class="col-lg-1">Nombre</td>
		<td class="col-lg-2">
		<?php print $this->form->reid; ?>
		<?php print $this->form->name; ?>
		</td>
		<td class="col-lg-1">Modulo</td>
		<td class="col-lg-2"><?php print $this->form->mid; ?></td>
	</tr>
	<tr>
		<td >Controlador</td>
		<td ><?php print $this->form->controller; ?></td>
		<td >Icono</td>
		<td ><?php print $this->form->imgicon; ?></td>
	</tr>
	<tr>
		<td >Estado</td>
		<td ><?php print $this->form->state; ?></td>
		<td ></td><td ></td>
	</tr>
</table>
</form>