<?php 
	$auth = Zend_Auth::getInstance();

	if (!$auth->hasIdentity()) {
		exit();
	}


	$sesion = $auth->getStorage()->read();
	$last_name = $sesion->infouser['fullname'];
	$module = $sesion->rol['module'];
	$rol_name = $sesion->rol['name'];
	$rol = $sesion->rid;
	$uid = $sesion->uid;
	$pid = $sesion->pid;

?>
<input type="hidden" id="rol" value="<?php print $rol ?>">

<header>
	<nav>
		<figure>
			<a href="/<?php print $module?>"><img class="img-rounded" src="/img/logo.jpg" alt="logo" width="80" height="60"></a>
		</figure>
		<div>
			<p><?php print $last_name?></p>
			<p><?php print $rol_name?></p>
		</div>
		<div>
			<a href="#" id="js_main-btn-menu"><span class="glyphicon glyphicon-align-justify"></span></a>
			<ul id="js_main-menu-ul">
				<li><a href="/<?php print $module ?>"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
				<li><a href="#"><span class="glyphicon glyphicon-user"></span> Mi Perfil </a></li>
				<li><a href="#"><span class="glyphicon glyphicon-envelope"></span> Notificaciones</a></li>
				<li><a href="/logout"><span class="glyphicon glyphicon-off "></span> Cerrar Sesión</a></li>
			</ul>
		</div>
	</nav>
</header>
<script type="text/javascript">
	$(function(){
		$("#js_main-btn-menu").on('click', function(e){
			e.preventDefault()
			$("#js_main-menu-ul").toggleClass('active')
		})		
	})
</script>