<?php $this->placeholder('Textnav')->append('<span class="glyphicon glyphicon-user"></span> Gestión Persona');?>
<?php $this->placeholder('Btnnav')->append('<a href="/" ><span class="glyphicon glyphicon-circle-arrow-left"></span></a>');?>
<style type="text/css">
	.header-person{
		display: flex;
		flex-wrap: wrap;
		justify-content: space-between;
	}   
</style>


<div class="header-person">
	<p class="text-muted"><span class="glyphicon glyphicon-info-sign text-primary"></span>  Buscar personas</p>
	<button class="btn btn-success js_new_person"><span class="glyphicon glyphicon-plus"></span> Nueva Persona</button>
</div>
<br>
<form name="frmFiltroDoc" id ="frmFiltroDoc" action="/admin/person/getperson" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal" >
	<table class="table table-hover">
		<tr>
			<td style="width: 30%" class="text-center">DNI</td>
			<td style="width: 70%" class="text-center">Nombres y Apellidos</td>			
		</tr>
		<tr>                    
			<td><?php echo $this->fm->pid ?></td>
			<td><?php echo $this->fm->name ?></td>
		</tr>
	</table>
</form>
<br>
<div id="cargadatos_"></div>

<div class="modal fade modalPerson" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title text-center text-primary"><b>Nueva Persona</b></h4>
			</div>
			<div class="modal-body">
				<div class='load_form_person'></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

	$("#pid").keypress(function (e) {
		if(e == 13 || e.which==13 || e.which==0){
			var codi =  $('#pid').val();
			count=codi.length;
			if (count==8){
				$('#cargadatos_').html("<center><img src='/img/spinner.gif'> Cargando... </center>");
				$('#name').val('')	
				$("#frmFiltroDoc").submit();
			}
			else{
				alert("Ingrese un DNI valido");
				$('#pid').val('');
			}
		}
	});

	$("#name").keypress(function (e) {
		if(e == 13 || e.which==13 || e.which==0){
			var nom =  $('#name').val();

			if (nom){
				$('#cargadatos_').html("<center><img src='/img/spinner.gif'> Cargando... </center>")
				$('#pid').val('')
				$("#frmFiltroDoc").submit()
			}
			else{
				alert("Ingrese algo en Apellidos y Nombres");
				$('#name').val('')
			}
		}
	})
	
	$("#frmFiltroDoc").submit(function(){
		$.ajax({
			url: $(this).attr('action'),
			type: 'POST',
			data: $(this).serialize(),
			success: function(data) {
				$('#cargadatos_').html(data);
			}
		}); 
		return false;
	})

	$(".js_new_person").on('click', function(){
		$(".modalPerson").modal('show')
	})

	$('.modalPerson').on('show.bs.modal', function (event) {
		$(".load_form_person").html("<center><img src='/img/spinner.gif'> Cargando...</center>")
		setTimeout(function(){
			$(".load_form_person").load('/admin/person/new')
		},500)
	})

	function validNumber(e) {
		var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
		return ((tecla > 47 && tecla < 58) || tecla == 8);
	} 
	function soloLetras(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
		especiales = [8,37,39,46];

		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			}
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial){
			return false;
		}
	}

</script>